[package]
name = "guessing"
version.workspace = true
authors.workspace = true
description = ""
edition.workspace = true

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
rayon = { workspace = true }
