[workspace]
resolver = '2'
members = [
    "crates/*",
]
default-members = ["crates/guessing"]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Thurston Zhu"]
rust-version = "1.83.0"
